### PR TITLE
fix: retry if eval fails

### LINKED ISSUE #144: Get "NOSCRIPT No matching script. Please use EVAL" when redis pod restarts.
### Description

Please consider adding a try catch around https://github.com/wyattjoh/rate-limit-redis/blob/effebd57bf943d3acfb3cdf3c4856c72383cd749/src/lib.ts#L114 and https://github.com/wyattjoh/rate-limit-redis/blob/effebd57bf943d3acfb3cdf3c4856c72383cd749/src/lib.ts#L121, so that when RedisNoScriptException happens, loadScript() can be invoked again to load the script into redis.

Current workaround:
```
const app = express()
class MyRedisStore extends RedisStore { 
    increment = async(key) => {
        let results = []
        try {
            results = await this.sendCommand(
                "EVALSHA",
                await this.loadedScriptSha1,
                "1",
                this.prefixKey(key),
                this.resetExpiryOnChange ? "1" : "0",
                this.windowMs.toString()
            );
        } catch (err) {
            this.loadedScriptSha1 = await this.loadScript()
            results = await this.sendCommand(
                "EVALSHA",
                await this.loadedScriptSha1,
                "1",
                this.prefixKey(key),
                this.resetExpiryOnChange ? "1" : "0",
                this.windowMs.toString()
            );
        }
      
        if (!Array.isArray(results)) {
            throw new TypeError("Expected result to be array of values");
        }
    
        if (results.length !== 2) {
            throw new Error(`Expected 2 replies, got ${results.length}`);
        }
    
        const totalHits = results[0];
        if (typeof totalHits !== "number") {
            throw new TypeError("Expected value to be a number");
        }
    
        const timeToExpire = results[1];
        if (typeof timeToExpire !== "number") {
            throw new TypeError("Expected value to be a number");
        }
    
        const resetTime = new Date(Date.now() + timeToExpire);
        return {
            totalHits,
            resetTime,
        };
    }
}

function apiLimiterDefault() {
    return rateLimit({
        ........
        store: new MyRedisStore({
            sendCommand: (...args) => xdrRedis.boot().handle().sendCommand(args),
        })
    })
}

app.get("/", [apiLimiterDefault()], (req, res) {
  return res.json({"hello": "world"})
})
```
(Basically just wrapping a try catch block around)

### Library version

3.0.1

### Node version

14.16.0

### Typescript version (if you are using it)

_No response_

### Module system

CommonJS

### Redis Client

redis 4.0.4

### PR DESCRIPTION
**Pull request by mifi**
## Related Issues

fixes #144

## What Does This PR Do?

retry if eval fails

## Checklist

- [x] The issues that this PR fixes/closes have been mentioned above.
- [x] What this PR adds/changes/removes has been explained.
- [ ] All tests (`npm run test`) pass.
- [ ] The linter and formatter (`npm run lint`) do not report any errors.
- [ ] All added/modified code has been commented, and
      methods/classes/constants/types have been annotated with TSDoc comments.
- [ ] If a new feature has been added or a bug has been fixed, tests have been
      added for the same.

### CODE REVIEW

**Review by antoniojps — APPROVED** [review]

**Comment by elizatlawy** [comment]
Any update on when this is going to be merged?

**Comment by elizatlawy** [comment]
Still relevant

**Comment by mifi** [comment]
@wyattjoh any chance to get this reviewed?

**Review by gamemaker1 — APPROVED** [review]
LGTM!

Apologies for the delay in getting this merged.

**Pull request merged**
